/* DO NOT MODIFY, THIS FILE IS AUTO GENERATED BY SCRIPTS.   
 * Generated at 2018年07月10日 17:55:52                                     
 */                                                         
#ifndef __AUTO_VERSION__
#define __AUTO_VERSION__

#define VERSION_STRING "v1.0.0-1-gcb26def-dirty"
#define VERSION_DESC   "180710_35752"

#endif
